# Generated by Django 5.1.2 on 2024-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DonorId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
