# Generated by Django 5.1.2 on 2024-12-16 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
