# Generated by Django 4.2 on 2024-12-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateoperations',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='donateoperations',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='donation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
