# Generated by Django 4.2 on 2024-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_deleteddonationlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteddonationlogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
