# Generated by Django 5.1.2 on 2024-12-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateoperations',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrescue.donation'),
        ),
        migrations.AlterField(
            model_name='donateoperations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
