# Generated by Django 5.1.3 on 2024-11-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0003_user_name_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('ItemId', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('DonationDate', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('DonorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrescue.donor')),
            ],
        ),
    ]
