# Generated by Django 5.1.3 on 2024-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ItemId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
