# Generated by Django 4.2 on 2024-12-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0004_alter_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='restaurant',
            field=models.CharField(default='Unknown Restaurant', max_length=100),
        ),
    ]
