# Generated by Django 4.2 on 2024-12-31 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0004_alter_deleteddonationlogs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reserved_quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
