# Generated by Django 5.1.3 on 2024-11-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0005_alter_donation_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='expiry_date',
            new_name='ExpiryDate',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
