# Generated by Django 4.2 on 2024-12-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0005_donation_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='reserved_quantity',
        ),
    ]
