# Generated by Django 5.1.3 on 2024-11-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0006_rename_expiry_date_donation_expirydate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='DonorId',
            new_name='Donor',
        ),
    ]
