# Generated by Django 5.1.2 on 2024-11-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0007_rename_donorid_donation_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='DonationDate',
            new_name='donationDate',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='Donor',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='ExpiryDate',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='DonorId',
            new_name='donorId',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CustomerId',
            new_name='customerId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
