# Generated by Django 5.1.3 on 2024-11-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0008_rename_donationdate_donation_donationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedbackText', models.TextField()),
                ('feedbackDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrescue.user')),
            ],
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='expiryDate',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='ItemId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donationDate',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.AddField(
            model_name='donation',
            name='item_name',
            field=models.CharField(default='Unknown Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProvideFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodrescue.feedback')),
            ],
            bases=('foodrescue.feedback',),
        ),
    ]
